#! /bin/sh
erlc /buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@2c4afe0e57b9.2024-03-12_19.08.42/make_test_dir.system_test.logs/run.2024-03-12_19.08.42/log_private/test.erl
read reply
echo $reply
