#!/bin/sh
PATH="/buildroot/otp/Erlang ∅⊤℞/erts-15.1.2/bin:$PATH"
typer --plt /buildroot/otp/lib/dialyzer/make_test_dir/ct_logs/ct_run.test_server@78b6bb0e19ca.2024-11-20_13.53.19/make_test_dir.dialyzer_test.logs/run.2024-11-20_13.53.21/log_private/dialyzer_plt /buildroot/otp/lib/dialyzer/make_test_dir/ct_logs/ct_run.test_server@78b6bb0e19ca.2024-11-20_13.53.19/make_test_dir.dialyzer_test.logs/run.2024-11-20_13.53.21/log_private/typer_test_module.erl
case $? in
  0) echo '_OK_';;
  *) echo '_ERROR_';;
esac
