{node,n1,node1@host1}.
{node,n2,node2@host2}.
{init,[n1],[{node_start,[{callback_module,cbm}]}]}.
{init,n2,[{node_start,[]}]}.
{init,all_nodes,{eval,{mod,func,[]}}}.
{label,"basic_compatible_nodes"}.
{label,n1,basic_compatible_nodes_1}.
{config,n1,"../cfgs/to1/x.cfg"}.
{config,n2,["../cfgs/to2/x.cfg","../cfgs/to2/y.cfg"]}.
{userconfig,{ct_testspec_2_SUITE,"cfg_str1"}}.
{userconfig,{ct_testspec_2_SUITE,"cfg_str2"}}.
{logdir,all_nodes,"../logs"}.
{logdir,master,"../master_logs"}.
{logopts,node2@host2,[no_nl]}.
{event_handler,master,evh1,[1]}.
{event_handler,[n1,n2],[evh2,evh3],[[2,3]]}.
{ct_hooks,all_nodes,[{cth_mod1,[]}]}.
{ct_hooks,[{cth_mod2,[]}]}.
{ct_hooks_order,config}.
{multiply_timetraps,node1@host1,2}.
{include,n1,"../../include"}.
{include,[n1,n2],["../tests/to1/include","../tests/to2/include"]}.
{suites,n1,"../tests/to1",[x_SUITE]}.
{groups,n1,"../tests/to1",y_SUITE,[g1,g2]}.
{cases,n1,"../tests/to1",y_SUITE,[tc1,tc2]}.
{skip_suites,n1,"../tests/to1",z_SUITE,"skipped"}.
{suites,n2,"../tests/to2",[x_SUITE,y_SUITE]}.
{skip_groups,n2,"../tests/to2",x_SUITE,[g1,g2],"skipped"}.
{skip_cases,n2,"../tests/to2",y_SUITE,[tc1,tc2],"skipped"}.
