#! /bin/sh
erlc /buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@b02f72690044.2024-03-15_14.58.55/make_test_dir.system_test.logs/run.2024-03-15_14.58.56/log_private/test.erl
read reply
echo $reply
