{node,t_1,t_1@ac22cca2be94}.
{node,t_2,t_2@ac22cca2be94}.
{node,t_3,t_3@ac22cca2be94}.
{node,t_4,t_4@ac22cca2be94}.
{node,t_5,t_5@ac22cca2be94}.
{include,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_master_SUITE_data/master/include"}.
{event_handler,master,
               [ct_test_support_eh],
               [{cbm,ct_test_support},{trace_level,50}]}.
{config,t_1,
        "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_master_SUITE_data/master/config.txt"}.
{config,t_2,
        "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_master_SUITE_data/master/config.txt"}.
{userconfig,t_3,
            {ct_config_xml,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_master_SUITE_data/master/config.xml"}}.
{userconfig,t_4,
            {ct_config_xml,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_master_SUITE_data/master/config.xml"}}.
{userconfig,t_5,
            {ct_config_xml,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_master_SUITE_data/master/config.xml"}}.
{config,master,
        "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_master_SUITE_data/master/config.txt"}.
{suites,[t_1,t_2,t_3,t_4,t_5],
        "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_master_SUITE_data/master",
        [master_SUITE]}.
{logdir,t_1,
        "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@ac22cca2be94.2024-11-26_09.55.59/make_test_dir.common_test_test.logs/run.2024-11-26_09.56.02/log_private/slave.t_1"}.
{logdir,t_2,
        "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@ac22cca2be94.2024-11-26_09.55.59/make_test_dir.common_test_test.logs/run.2024-11-26_09.56.02/log_private/slave.t_2"}.
{logdir,t_3,
        "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@ac22cca2be94.2024-11-26_09.55.59/make_test_dir.common_test_test.logs/run.2024-11-26_09.56.02/log_private/slave.t_3"}.
{logdir,t_4,
        "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@ac22cca2be94.2024-11-26_09.55.59/make_test_dir.common_test_test.logs/run.2024-11-26_09.56.02/log_private/slave.t_4"}.
{logdir,t_5,
        "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@ac22cca2be94.2024-11-26_09.55.59/make_test_dir.common_test_test.logs/run.2024-11-26_09.56.02/log_private/slave.t_5"}.
{logdir,master,
        "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@ac22cca2be94.2024-11-26_09.55.59/make_test_dir.common_test_test.logs/run.2024-11-26_09.56.02/log_private/"}.
{init,t_1,
      [{node_start,[{startup_functions,[]},
                    {monitor_master,true},
                    {boot_timeout,10},
                    {init_timeout,10},
                    {startup_timeout,10},
                    {env,[{"THIS_MUST_BE_SET","yes"},
                          {"SO_MUST_THIS","value"}]}]},
       {eval,{erlang,nodes,[]}}]}.
{init,t_2,
      [{node_start,[{startup_functions,[]},
                    {monitor_master,true},
                    {boot_timeout,10},
                    {init_timeout,10},
                    {startup_timeout,10},
                    {env,[{"THIS_MUST_BE_SET","yes"},
                          {"SO_MUST_THIS","value"}]}]},
       {eval,{erlang,nodes,[]}}]}.
{init,t_3,
      [{node_start,[{startup_functions,[]},
                    {monitor_master,true},
                    {boot_timeout,10},
                    {init_timeout,10},
                    {startup_timeout,10},
                    {env,[{"THIS_MUST_BE_SET","yes"},
                          {"SO_MUST_THIS","value"}]}]},
       {eval,{erlang,nodes,[]}}]}.
{init,t_4,
      [{node_start,[{startup_functions,[]},
                    {monitor_master,true},
                    {boot_timeout,10},
                    {init_timeout,10},
                    {startup_timeout,10},
                    {env,[{"THIS_MUST_BE_SET","yes"},
                          {"SO_MUST_THIS","value"}]}]},
       {eval,{erlang,nodes,[]}}]}.
{init,t_5,
      [{node_start,[{startup_functions,[]},
                    {monitor_master,true},
                    {boot_timeout,10},
                    {init_timeout,10},
                    {startup_timeout,10},
                    {env,[{"THIS_MUST_BE_SET","yes"},
                          {"SO_MUST_THIS","value"}]}]},
       {eval,{erlang,nodes,[]}}]}.
