{cases,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/suites_1",
       simple_1_SUITE,
       [tc1,tc2]}.
{cases,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/suites_1",
       simple_2_SUITE,
       [tc2,tc1]}.
{skip_cases,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/suites_1",
            simple_1_SUITE,
            [tc1],
            "SKIPPED!"}.
{skip_cases,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/suites_1",
            simple_2_SUITE,tc2,"SKIPPED!"}.
