#!/bin/sh
ERLC_EMULATOR='/buildroot/otp/erts/make_test_dir/Erlang ∅⊤℞/erts-15.1.2/bin/erl'
export ERLC_EMULATOR
"/buildroot/otp/erts/make_test_dir/Erlang ∅⊤℞/erts-15.1.2/bin/erlc" -I/buildroot/otp/erts/make_test_dir/system_test/erlc_SUITE_data/include -o/buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@24d245a88236.2024-11-07_13.11.00/make_test_dir.system_test.logs/run.2024-11-07_13.11.01/log_private/  -enable-feature experimental_ftr_1 -enable-feature experimental_ftr_2 /buildroot/otp/erts/make_test_dir/system_test/erlc_SUITE_data/src/ignorant.erl
case $? in
  0) echo '_OK_';;
  *) echo '_ERROR_';;
esac
