#! /bin/sh
erlc /buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@cc7b5b185177.2024-07-04_20.47.16/make_test_dir.system_test.logs/run.2024-07-04_20.47.16/log_private/test.erl
read reply
echo $reply
