#!/bin/sh
ERLC_EMULATOR='erl'
export ERLC_EMULATOR
"/buildroot/otp/erts/make_test_dir/Erlang ∅⊤℞/erts-15.1.1/bin/erlc" -I/buildroot/otp/erts/make_test_dir/system_test/erlc_SUITE_data/include -o/buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@4bcc9176750b.2024-10-16_11.02.11/make_test_dir.system_test.logs/run.2024-10-16_11.02.12/log_private/  -enable-feature experimental_ftr_1 -enable-feature experimental_ftr_2 /buildroot/otp/erts/make_test_dir/system_test/erlc_SUITE_data/src/ignorant.erl
case $? in
  0) echo '_OK_';;
  *) echo '_ERROR_';;
esac
