{groups,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
        groups_11_SUITE,test_group_1a,
        {cases,[testcase_1a,testcase_1b]}}.
{groups,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
        groups_11_SUITE,test_group_1b,
        {cases,[testcase_1b,testcase_1a]}}.
{skip_groups,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
             groups_11_SUITE,test_group_1a,
             {cases,testcase_1b},
             "SKIPPED!"}.
{skip_groups,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
             groups_11_SUITE,test_group_1b,
             {cases,[testcase_1a]},
             "SKIPPED!"}.
