%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module Seq.

-ifndef(_SEQ_HRL_).
-define(_SEQ_HRL_, true).

-record('a_Seq', {
  bool,
  boolCon,
  boolPri,
  boolApp,
  boolExpCon,
  boolExpPri,
  boolExpApp
}).

-record('a_Seq1', {
  bool1,
  int1,
  seq1
}).

-record('a_Seq2', {
  seq2,
  bool2,
  int2
}).

-record('a_Seq3', {
  bool3,
  seq3,
  int3
}).

-record('a_Seq4', {
  seq41,
  seq42,
  seq43
}).

-record('a_SeqDef1', {
  bool1 = asn1_DEFAULT,
  int1,
  seq1 = asn1_DEFAULT
}).

-record('a_SeqDef2', {
  seq2 = asn1_DEFAULT,
  bool2,
  int2
}).

-record('a_SeqDef3', {
  bool3 = asn1_DEFAULT,
  seq3 = asn1_DEFAULT,
  int3 = asn1_DEFAULT
}).

-record('a_SeqOpt1', {
  bool1 = asn1_NOVALUE,
  int1,
  seq1 = asn1_NOVALUE
}).

-record('a_SeqOpt2', {
  seq2 = asn1_NOVALUE,
  bool2,
  int2
}).

-record('a_SeqOpt3', {
  bool3 = asn1_NOVALUE,
  seq3 = asn1_NOVALUE,
  int3 = asn1_NOVALUE
}).

-record('a_SeqIn', {
  boolIn = asn1_NOVALUE,
  intIn = asn1_DEFAULT
}).

-record('a_SeqS1', {
  boolS1,
  intS1,
  seqS1
}).

-record('a_SeqS1_seqS1', {
  boolIn,
  intIn
}).

-record('a_SeqS2', {
  seqS2,
  boolS2,
  intS2
}).

-record('a_SeqS2_seqS2', {
  boolIn,
  intIn
}).

-record('a_SeqS3', {
  boolS3,
  seqS3,
  intS3
}).

-record('a_SeqS3_seqS3', {
  boolIn,
  intIn
}).

-record('a_SeqImp1', {
  set,
  bool,
  int
}).

-record('a_SeqImp2', {
  bool,
  set,
  int
}).

-record('a_SeqImp3', {
  bool,
  int,
  set
}).

-record('a_SeqCompOf', {
  %% with extensions
  boolS3,
  seqS3,
  intS3
}).

-record('a_SeqCompOf_seqS3', {
  boolIn,
  intIn
}).

-endif. %% _SEQ_HRL_
