#!/bin/sh
PATH="/buildroot/otp/Erlang ∅⊤℞/erts-15.1.2/bin:$PATH"
typer --plt /buildroot/otp/lib/dialyzer/make_test_dir/ct_logs/ct_run.test_server@b27fcb63efff.2024-11-15_15.10.53/make_test_dir.dialyzer_test.logs/run.2024-11-15_15.10.55/log_private/dialyzer_plt /buildroot/otp/lib/dialyzer/make_test_dir/ct_logs/ct_run.test_server@b27fcb63efff.2024-11-15_15.10.53/make_test_dir.dialyzer_test.logs/run.2024-11-15_15.10.55/log_private/typer_test_module.erl
case $? in
  0) echo '_OK_';;
  *) echo '_ERROR_';;
esac
