#! /bin/sh
erlc /buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@e93dc2a9af49.2024-04-26_13.23.08/make_test_dir.system_test.logs/run.2024-04-26_13.23.08/log_private/test.erl
read reply
echo $reply
