{merge_tests,false}.
{cases,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
       groups_12_SUITE,
       [testcase_1a]}.
{cases,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_2",
       groups_22_SUITE,
       [testcase_1]}.
{cases,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
       groups_12_SUITE,
       [testcase_1b]}.
