{groups,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
        groups_11_SUITE,
        [test_group_1a,test_group_1b]}.
{skip_groups,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
             groups_11_SUITE,test_group_1b,
             {cases,all},
             "SKIPPED!"}.
{skip_groups,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_testspec_1_SUITE_data/groups_1",
             groups_11_SUITE,test_group_1a,
             {cases,all},
             "SKIPPED!"}.
