#! /bin/sh
erlc /buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@7bfc4dfb0e57.2024-07-04_11.48.43/make_test_dir.system_test.logs/run.2024-07-04_11.48.43/log_private/test.erl
read reply
echo $reply
