%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module Comment.

-ifndef(_COMMENT_HRL_).
-define(_COMMENT_HRL_, true).

-record('Seq', {
  a,
  b
}).

-endif. %% _COMMENT_HRL_
