%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module MyMerge.

-ifndef(_MYMERGE_HRL_).
-define(_MYMERGE_HRL_, true).

-record('Seq2', {
  a,
  b
}).

-endif. %% _MYMERGE_HRL_
