%% Generated by the Erlang ASN.1 compiler. Version: 5.3.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module P-Record.

-ifndef(_P_RECORD_HRL_).
-define(_P_RECORD_HRL_, true).

-record('PersonnelRecord', {
  name,
  title,
  number,
  dateOfHire,
  nameOfSpouse,
  children = asn1_DEFAULT
}).

-record('ChildInformation', {
  name,
  dateOfBirth
}).

-record('Name', {
  givenName,
  initial,
  familyName
}).

-define('v', {'PersonnelRecord',{'Name',[74,111,104,110],[80],[83,109,105,116,104]},[68,105,114,101,99,116,111,114],51,[49,57,55,49,48,57,49,55],{'Name',[77,97,114,121],[84],[83,109,105,116,104]},[{'ChildInformation',{'Name',[82,97,108,112,104],[84],[83,109,105,116,104]},[49,57,53,55,49,49,49,49]},{'ChildInformation',{'Name',[83,117,115,97,110],[66],[74,111,110,101,115]},[49,57,53,57,48,55,49,55]}]}).
-endif. %% _P_RECORD_HRL_
