#! /bin/sh
erlc /buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@8b21410acdf7.2024-09-10_15.44.45/make_test_dir.system_test.logs/run.2024-09-10_15.44.45/log_private/test.erl
read reply
echo $reply
