#!/bin/sh
ERLC_EMULATOR='erl'
export ERLC_EMULATOR
"/buildroot/otp/erts/make_test_dir/Erlang ∅⊤℞/erts-14.1.1/bin/erlc" -I/buildroot/otp/erts/make_test_dir/system_test/erlc_SUITE_data/include -o/buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@a0dbc64c20d3.2023-11-09_15.13.59/make_test_dir.system_test.logs/run.2023-11-09_15.14.00/log_private/  -enable-feature experimental_ftr_1 -enable-feature experimental_ftr_2 /buildroot/otp/erts/make_test_dir/system_test/erlc_SUITE_data/src/ignorant.erl
case $? in
  0) echo '_OK_';;
  *) echo '_ERROR_';;
esac
