{define,'HOST',eniac}.
{define,'NODE1',testnode1}.
{define,'NODE2',testnode2}.
{define,'NODES',['NODE1@HOST','NODE2@HOST']}.
{define,'TOPDIR',".."}.
{define,'TO1',"to1"}.
{define,'TO2',"to2"}.
{define,'LOGDIR',"'TOPDIR'/logdir"}.
{define,'LOGDIR1',"'TOPDIR'/logdir1"}.
{define,'LOGDIR2',"'TOPDIR'/logdir2"}.
{define,'CFGDIR',"'TOPDIR'/cfgs"}.
{define,'CFGFILES',["cfgX","cfgY"]}.
{define,'TESTDIR',"'TOPDIR'/test"}.
{define,'TO1DIR',"'TESTDIR'/'TO1'"}.
{define,'TO2DIR',"'TESTDIR'/'TO2'"}.
{define,'EXSUITE',ex_SUITE}.
{define,'EXGRS',[g1,g2]}.
{logdir,'LOGDIR'}.
{logdir,'NODE1@HOST','LOGDIR1'}.
{logdir,'NODE2@HOST','LOGDIR2'}.
{config,["a.cfg","b.cfg"]}.
{config,'NODES',"./'CFGDIR'/c.cfg"}.
{config,'CFGDIR',["d.cfg","e.cfg"]}.
{config,'NODE2@HOST','CFGDIR','CFGFILES'}.
{suites,'NODE1@HOST','TO1DIR',all}.
{suites,'NODES','TO2DIR',all}.
{groups,'TO1DIR','EXSUITE','EXGRS'}.
