#! /bin/sh
erlc /buildroot/otp/erts/make_test_dir/ct_logs/ct_run.test_server@c260bf1469f2.2025-01-30_18.25.34/make_test_dir.system_test.logs/run.2025-01-30_18.25.34/log_private/test.erl
read reply
echo $reply
