{label,"basic_compatible_no_nodes"}.
{alias,to1,"../tests/to1"}.
{alias,to2,"../tests/to2"}.
{config,"../cfgs/to1/x.cfg"}.
{config,["../cfgs/to2/x.cfg","../cfgs/to2/y.cfg"]}.
{userconfig,{ct_testspec_2_SUITE,"cfg_str1"}}.
{userconfig,{ct_testspec_2_SUITE,"cfg_str2"}}.
{logdir,"../logs"}.
{logopts,[no_nl]}.
{event_handler,evh1,[1]}.
{event_handler,[evh2,evh3],[[2,3]]}.
{ct_hooks,[{cth_mod1,[]}]}.
{ct_hooks,[{cth_mod2,[]}]}.
{ct_hooks_order,config}.
{multiply_timetraps,2}.
{include,"../../include"}.
{include,["../tests/to1/include","../tests/to2/include"]}.
{suites,to1,[x_SUITE]}.
{groups,to1,y_SUITE,[g1,g2]}.
{cases,to1,y_SUITE,[tc1,tc2]}.
{skip_suites,to1,z_SUITE,"skipped"}.
{suites,to2,[x_SUITE,y_SUITE]}.
{skip_groups,to2,x_SUITE,[g1,g2],"skipped"}.
{skip_cases,to2,y_SUITE,[tc1,tc2],"skipped"}.
