#!/bin/sh
PATH="/buildroot/otp/Erlang ∅⊤℞/erts-15.2/bin:$PATH"
typer --plt /buildroot/otp/lib/dialyzer/make_test_dir/ct_logs/ct_run.test_server@ecf8287c9ea7.2025-01-09_11.09.26/make_test_dir.dialyzer_test.logs/run.2025-01-09_11.09.28/log_private/dialyzer_plt /buildroot/otp/lib/dialyzer/make_test_dir/ct_logs/ct_run.test_server@ecf8287c9ea7.2025-01-09_11.09.26/make_test_dir.dialyzer_test.logs/run.2025-01-09_11.09.28/log_private/typer_test_module.erl
case $? in
  0) echo '_OK_';;
  *) echo '_ERROR_';;
esac
